# Site settings
title: My Free Blog
description: A blog about Freeruzy
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Freeruzy
user_description: 自创的英文词语当做自己的名字真的很Cooooool,Chinglish就是强,一个小小程序,谁晓得会不会就突然BigBang改变世界,改变一切.人总是要有梦想的，要不
和咸鱼有什么区别.人不犯我我不犯人,笑呵呵.
user_title: 付忠雨
email: 262578284@qq.com
twitter_username: freeruzy
github_username:  freeruzy
gplus_username:  freeruzy

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
